{{- if .Values.backupA }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ include "maplarge.fullname" . }}
  namespace: velero
  labels:
    application: {{ .Release.Name | quote }}
    {{- include "maplarge.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.backup.scheduleCronExpression | quote }}
  template:
    includedNamespaces:
    - {{- .Release.Namespace | quote }}
    includedResources:
    - '*'
    {{- if .Values.backup.storageLocation }}
    storageLocation: {{ .Values.backup.storageLocation }}
    {{- end }}
    ttl: {{ .Values.backup.retentionDurationExpression }}
    hooks:
      resources:
      - name: before-pv-backup
        includedNamespaces:
        - {{- .Release.Namespace | quote }}
        includedResources:
        - pods
        labelSelector:
          matchLabels:
            {{- include "maplarge.selectorLabels" . | nindent 8 }}
            statefulset.kubernetes.io/pod-name: {{- printf "%s-0" "maplarge.fullname" }}
    {{- toYaml . | nindent 4 }}
{{- end }}