{{- $imagePullSecretName := include "maplarge.pullSecretName" . -}}
{{ $dockerconfigjson := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace ( include "maplarge.pullSecretName" . ) ) }}
{{- if $secret }}
  {{- $dockerconfigjson = index $secret.data ".dockerconfigjson" }}
{{- else }}
  {{- if .Values.dockerCredentials -}}
  {{- with .Values.dockerCredentials }}
  {{- $dockerconfigjson = printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.dockerCredentials -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName }}
  labels:
    application: {{ .Release.Name | quote }}
    {{- include "maplarge.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson }}
{{- end }}