apiVersion: v1
kind: Service
metadata:
  name: {{ include "maplarge.headlessServiceName" . }}
  labels:
    app.kubernetes.io/name: dns-headless-service
    app.kubernetes.io/component: cluster-dns
    app.kubernetes.io/part-of: {{ include "maplarge.name" . }}
    application: {{ .Release.Name | quote }}
    {{- include "maplarge.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  clusterIP: None
  sessionAffinity: None
  publishNotReadyAddresses: true
  ports:
    - port: 80
      targetPort: {{ default "80" .Values.service.targetPort }}
      protocol: TCP
      name: web
  selector:
    {{- include "maplarge.selectorLabels" . | nindent 4 }}
