{{- if or .Values.serviceAccount.create .Values.notebooks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maplarge.serviceAccountName" . }}
  labels:
    application: {{ .Release.Name | quote }}
{{- end }}