{{- if .Values.ingress.enabled -}}
{{- $annotations := .Values.ingress.annotations -}}
{{- $fullName := include "maplarge.fullname" . -}}
{{- $ingressName := include "maplarge.ingressName" . -}}
{{- $loadBalancerServiceName := include "maplarge.balancerServiceName" . -}}
{{ $policyHost := include "maplarge.hostname" . }}
{{- $cspPolicy := "" }}
{{- if .Values.contentSecurityPolicy.enabled }}
{{- $cspPolicy = include "maplarge.contentSecurityPolicy" (dict "hostName" $policyHost "csp" .Values.contentSecurityPolicy) | trim -}}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    application: {{ .Release.Name | quote }}
    {{- include "maplarge.labels" . | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
    {{- if .Values.contentSecurityPolicy.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers {{ (printf "%s" $cspPolicy) | quote }};
    {{- end }}
spec:
{{- with .Values.ingress }}
  ingressClassName: {{ .class }}
{{- range .hosts }}
{{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .baseHostname | quote | lower }}
{{- $baseHostname := .baseHostname | lower -}}
{{- range untilStep 0 (int .prefixes) 1 }}
        - {{ (printf "%d%s" . $baseHostname) | lower | quote }}
{{- end }}
{{- if .tls.secretName }}
      secretName: {{ .tls.secretName }}
{{- end }}
{{- end }}
{{- end }}
  rules:
{{- range .hosts }}
    - host: {{ .baseHostname | lower | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $loadBalancerServiceName }}
                port:
                  number: 80
{{- $baseHostname := .baseHostname -}}
{{- range untilStep 0 (int .prefixes) 1}}
    - host: {{ printf "%d%s" . $baseHostname | lower }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $loadBalancerServiceName }}
                port:
                  number: 80
{{- end }}
{{- end }}
{{- end }}
{{- end }}



