{{- if .Values.notebooks.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "maplarge.serviceAccountName" . }}:notebooks
  labels:
    application: {{ .Release.Name | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "maplarge.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "maplarge.serviceAccountName" . }}:notebooks
{{- end -}}