{{ $rootPassword := "" }}
{{ $existingPassword := "" }}
{{ $valuePassword := "" }}  
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace ( include "maplarge.rootPasswordSecretName" . ) ) }}
{{- if $secret }}
  {{- $existingPassword = index $secret.data.rootPassword }}
  {{- if .Values.rootPassword}}
    {{- $valuePassword = .Values.rootPassword | b64enc }}
    {{- if eq $existingPassword $valuePassword }}
    {{- $rootPassword = $existingPassword }}
    {{- else }}
    {{- $rootPassword = $valuePassword }}
    {{- end }}
  {{- else }}
    {{- $rootPassword = $existingPassword }}
  {{- end }}
{{- else }}
  {{- if .Values.rootPassword }}
  {{- $rootPassword = .Values.rootPassword |b64enc }}
  {{- else }}
  {{- $rootPassword = (randAlpha 32) | b64enc}}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maplarge.rootPasswordSecretName" . }}
  labels:
    application: {{ .Release.Name | quote }}
    {{- include "maplarge.labels" . | nindent 4 }}
type: Opaque
data:
  rootPassword: {{ $rootPassword }}
